# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/lessons/20220916" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/lessons/20220923/robin-app"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/lessons/20220930/server"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/lessons/20221007/server"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/lessons/20221014"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/lessons/20221014/frontend"
    schedule:
      interval: "weekly"
